-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;
use work.axisStream_slv32.all;


entity axiPrint is 
  port(
    Axi_in_s2m :  out  axiStream_slv32_s2m := axiStream_slv32_s2m_null;
    Axi_in_m2s :  in  axiStream_slv32_m2s := axiStream_slv32_m2s_null;
    clk :  in  std_logic := '0'
  );
end entity;



architecture rtl of axiPrint is

--------------------------axiPrint-----------------
  signal i_buff : std_logic_vector(31 downto 0) := (others => '0'); 
-------------------------- end axiPrint-----------------

begin

  -----------------------------------
  proc : process(clk) is
    variable axiSalve : axiStream_slv32_slave := axiStream_slv32_slave_null;
    variable axiSalve_buff : std_logic_vector(31 downto 0) := (others => '0');
    begin
      if rising_edge(clk) then 
        pull( self  =>  axiSalve, rx => Axi_in_m2s);
    
        if (isReceivingData_0(self => axiSalve)) then 
          read_data_00(self => axiSalve, dataOut => axiSalve_buff);
          i_buff <= axiSalve_buff;
          
        end if;
          push( self  =>  axiSalve, rx => Axi_in_s2m);
    end if;
    
    end process;
  
end architecture;