 
    -- XGEN: Autogenerated File

    library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;



    package signed16_a_pack is 
    type signed16_a is array (natural range <>) of signed(15 downto 0);
    end signed16_a_pack;

    package body signed16_a_pack is

    end signed16_a_pack;
    