 
    -- XGEN: Autogenerated File

    library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;
use work.v_symbol_pack.all;



    package signed8_a_pack is 
    type signed8_a is array (natural range <>) of signed(7 downto 0);
    end signed8_a_pack;

    package body signed8_a_pack is

    end signed8_a_pack;
    