-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;


package span_t2_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class span_t2 -------------------------

type span_t2 is record 
    start : std_logic_vector(7 downto 0);
    stop : std_logic_vector(7 downto 0);
end record;
    
    
  constant span_t2_null : span_t2:= (
    start => std_logic_vector(to_unsigned(3, 8)),
    stop => std_logic_vector(to_unsigned(48, 8))
  );


    type span_t2_a is array (natural range <>) of span_t2;
        

  procedure pull (self : inout span_t2; signal data_IO :  in  span_t2);
  procedure push (self : inout span_t2; signal data_IO :  out  span_t2);
  function isAfterRange_11 (Signal self :   span_t2; signal counter :   std_logic_vector) return boolean;
  function isBeforeRange_11 (Signal self :   span_t2; signal counter :   std_logic_vector) return boolean;
  function isInRange_11 (Signal self :   span_t2; signal counter :   std_logic_vector) return boolean;
------- End Psuedo Class span_t2 -------------------------
-------------------------------------------------------------------------


end span_t2_pack;


package body span_t2_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class span_t2 -------------------------
procedure pull (self : inout span_t2; signal data_IO :  in  span_t2) is
   
  begin 
 self  := data_IO; 
end procedure;

procedure push (self : inout span_t2; signal data_IO :  out  span_t2) is
   
  begin 
 data_IO  <=  self; 
end procedure;

function isInRange_11 (Signal self :   span_t2; signal counter :   std_logic_vector) return boolean is
   
  begin 
 return ( self.start <= counter and counter <= self.stop) ;
   
end function;

function isBeforeRange_11 (Signal self :   span_t2; signal counter :   std_logic_vector) return boolean is
   
  begin 
 return counter < self.start;
   
end function;

function isAfterRange_11 (Signal self :   span_t2; signal counter :   std_logic_vector) return boolean is
   
  begin 
 return self.stop < counter;
   
end function;

------- End Psuedo Class span_t2 -------------------------
  -------------------------------------------------------------------------


end span_t2_pack;

