-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.addr_data_pack.all;
use work.argg_hdl_core.all;
use work.optional_t_pack.all;
use work.ram_handle_master_pack.all;
use work.ram_handler_pack.all;
use work.slv32_a_pack.all;
use work.small_buffer_pack.all;


entity ramHandler_tb is 
end entity;



architecture rtl of ramHandler_tb is

--------------------------ramHandler_tb-----------------
  signal addr_out : std_logic_vector(31 downto 0) := (others => '0'); 
  signal adr : std_logic_vector(31 downto 0) := (others => '0'); 
  signal data : std_logic_vector(31 downto 0) := (others => '0'); 
  signal data_out : std_logic_vector(31 downto 0) := (others => '0'); 
--------------------------clkgen-----------------
  signal clkgen_clk : std_logic := '0'; 
-------------------------- end clkgen-----------------
--------------------------ram-----------------
  signal ram_DataIO_s2m : ram_handler_s2m := ram_handler_s2m_null;
  signal ram_DataIO_m2s : ram_handler_m2s := ram_handler_m2s_null;
  signal ram_clk : std_logic := '0'; 
-------------------------- end ram-----------------
-------------------------- end ramHandler_tb-----------------

begin
  -- begin architecture
  
-----------------------------------
proc : process(clkgen_clk) is
  variable ram_master : ram_handle_master := ram_handle_master_null;
  variable data_out_opt : optional_t := optional_t_null;
  begin
    if rising_edge(clkgen_clk) then 
      pull( self  =>  ram_master, tx => ram_DataIO_s2m);
  data <= data + 10;
    adr <= adr + 1;
    
      if (( ready_to_send_0(self => ram_master) and adr < 10) ) then 
        send_data_011(self => ram_master, adr => adr, data => data);
        
      end if;
    
      if (adr > 10) then 
        request_data_011(self => ram_master, adr => addr_out, data => data_out);
        request_data_010(self => ram_master, adr => addr_out, data => data_out_opt);
        
        if (to_bool(data_out_opt) ) then 
          addr_out <= addr_out + 1;
          
        end if;
        
      end if;
    
      if (addr_out > 8) then 
        addr_out <=  (others => '0');
        
      end if;
        push( self  =>  ram_master, tx => ram_DataIO_m2s);
  end if;
  
  end process;
  -- end architecture

  clkgen : entity work.clk_generator port map (
    clk => clkgen_clk
  );
  
  ram : entity work.ram_block port map (
    DataIO_s2m => ram_DataIO_s2m,
    DataIO_m2s => ram_DataIO_m2s,
    clk => ram_clk
  );
  ram_clk <= clkgen_clk;
  
end architecture;