-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.addr_data_pack.all;
use work.argg_hdl_core.all;


package small_buffer_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class small_buffer -------------------------

type small_buffer is record 
    count : integer;
    count_old : integer;
    head : integer;
    mem : addr_data_a(0 to 10 - 1 );
    tail : integer;
    tail_old : integer;
end record;
    
    
  constant small_buffer_null : small_buffer:= (
    count => 0,
    count_old => 0,
    head => 0,
    mem => (others => addr_data_null),
    tail => 0,
    tail_old => 0
  );


    type small_buffer_a is array (natural range <>) of small_buffer;
        

-- v_list getHeader
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
  procedure set_value_00_lshift (self :  inout  small_buffer; rhs :  inout  addr_data);
  function length (self :   small_buffer) return integer;
  function ready_to_send_0 (self :   small_buffer) return boolean;
  function length_0 (self :   small_buffer) return integer;
  procedure get_value_00_rshift (self :  inout  small_buffer; rhs :  inout  addr_data);
  function isReceivingData_0 (self :   small_buffer) return boolean;
  procedure re_read_0 (self :  inout  small_buffer);
  procedure reset_0 (self :  inout  small_buffer);
------- End Psuedo Class small_buffer -------------------------
-------------------------------------------------------------------------


end small_buffer_pack;


package body small_buffer_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class small_buffer -------------------------
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
procedure reset_0 (self :  inout  small_buffer) is
   
  begin 
 self.head := 0;
  self.tail := 0;
  self.count := 0;
   
end procedure;

procedure re_read_0 (self :  inout  small_buffer) is
   
  begin 
 self.tail := self.tail_old;
  self.count := self.count_old;
   
end procedure;

function isReceivingData_0 (self :   small_buffer) return boolean is
   
  begin 
 return self.count > 0;
   
end function;

procedure get_value_00_rshift (self :  inout  small_buffer; rhs :  inout  addr_data) is
   
  begin 
 rhs := addr_data_null;
  
    if (self.count > 0) then 
      rhs := self.mem(self.tail);
      self.tail := self.tail + 1;
      self.count := self.count - 1;
      
    end if;
  
    if (self.tail > self.mem'length - 1) then 
      self.tail := 0;
      
    end if;
   
end procedure;

function length_0 (self :   small_buffer) return integer is
   
  begin 
 return self.mem'length;
   
end function;

function ready_to_send_0 (self :   small_buffer) return boolean is
   
  begin 
 return self.count < self.mem'length;
   
end function;

function length (self :   small_buffer) return integer is
   
  begin 
 return self.mem'length;
   
end function;

procedure set_value_00_lshift (self :  inout  small_buffer; rhs :  inout  addr_data) is
   
  begin 
 
    if (ready_to_send_0(self => self)) then 
      self.mem(self.head) := rhs;
      self.head := self.head + 1;
      self.count := self.count + 1;
      
      if (self.head > self.mem'length - 1) then 
        self.head := 0;
        
      end if;
      
    end if;
  self.tail_old := self.tail;
  self.count_old := self.count;
   
end procedure;

------- End Psuedo Class small_buffer -------------------------
  -------------------------------------------------------------------------


end small_buffer_pack;

