-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;
use work.axisStream_slv32.all;


entity d_source is 
  port(
    clk :  in  std_logic := '0';
    data_out_s2m :  in  axiStream_slv32_s2m := axiStream_slv32_s2m_null;
    data_out_m2s :  out  axiStream_slv32_m2s := axiStream_slv32_m2s_null
  );
end entity;



architecture rtl of d_source is

--------------------------d_source-----------------
-------------------------- end d_source-----------------

begin
  -- begin architecture
  -- end architecture

end architecture;