-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;


package optional_t_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class optional_t -------------------------

type optional_t is record 
    data : std_logic_vector;
    valid : std_logic;
end record;
    
    
  constant optional_t_null : optional_t:= (
    data => (others => '0'),
    valid => '0'
  );


    type optional_t_a is array (natural range <>) of optional_t;
        

-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
  function to_bool (self :   optional_t) return boolean;
  procedure set_inValid_0 (self :  inout  optional_t);
  procedure reset_0 (self :  inout  optional_t);
  function is_valid_0 (self :   optional_t) return boolean;
------- End Psuedo Class optional_t -------------------------
-------------------------------------------------------------------------


end optional_t_pack;


package body optional_t_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class optional_t -------------------------
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
function is_valid_0 (self :   optional_t) return boolean is
   
  begin 
 return self.valid = '1';
   
end function;

procedure reset_0 (self :  inout  optional_t) is
   
  begin 
 self.valid := '0';
   
end procedure;

procedure set_inValid_0 (self :  inout  optional_t) is
   
  begin 
 self.valid := '0';
   
end procedure;

function to_bool (self :   optional_t) return boolean is
   
  begin 
 return is_valid_0(self => self);
   
end function;

------- End Psuedo Class optional_t -------------------------
  -------------------------------------------------------------------------


end optional_t_pack;

