-- XGEN: Autogenerated File



entity InputDelay_tb is 
end entity;



architecture rtl of InputDelay_tb is

--------------------------InputDelay_tb-----------------
-------------------------- end InputDelay_tb-----------------

begin

end architecture;