-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.hlpydlcore.all;
use work.register_t_pack.all;


package klm_globals_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class klm_globals -------------------------

type klm_globals is record 
    clk : std_logic;
    reg : register_t;
    rst : std_logic;
end record;
    
    
  constant klm_globals_null : klm_globals:= (
    clk => '0',
    reg => register_t_null,
    rst => '0'
  );


    type klm_globals_a is array (natural range <>) of klm_globals;
        

  procedure pull (self : inout klm_globals; signal data_IO :  in  klm_globals);
  procedure push (self : inout klm_globals; signal data_IO :  out  klm_globals);
------- End Psuedo Class klm_globals -------------------------
-------------------------------------------------------------------------


end klm_globals_pack;


package body klm_globals_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class klm_globals -------------------------
procedure pull (self : inout klm_globals; signal data_IO :  in  klm_globals) is
   
  begin 
 self  := data_IO; 
end procedure;

procedure push (self : inout klm_globals; signal data_IO :  out  klm_globals) is
   
  begin 
 data_IO  <=  self; 
end procedure;

------- End Psuedo Class klm_globals -------------------------
  -------------------------------------------------------------------------


end klm_globals_pack;

